### ISSUE TITLE
Cannot install on macbook High sierra

### ISSUE THREAD

**Issue by sr6033** [Dsudzy/passport-local-postgres#1]
On trying to install it, I get the following error.

![image](https://user-images.githubusercontent.com/15799589/47833229-b92c9980-ddbf-11e8-9350-43466173ef38.png)
![image](https://user-images.githubusercontent.com/15799589/47833248-c47fc500-ddbf-11e8-8734-a38b4c2a44bc.png)

**Comment by dsudzy** [comment]
I'm not 100% sure but your issue seems to be with node-gyp. From the stack trace I believe node-gyp it is trying to make a folder and cannot. Can you try to install using sudo?

**Comment by sr6033** [comment]
It is generally advised not to use sudo. Let me check another way.
